version: '3.4'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: interview
    image: vinbigdata-interview/flask-python:3.10
    restart: unless-stopped
    expose:
      - 5001
    ports:
      - 5001:5001
    environment:
      APP_ENV: "development"
      APP_DEBUG: "True"
      APP_PORT: 5001
    volumes:
      - appdata:/var/www
    networks:
      - backend
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    command: mongod
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: vinbigdata_interview
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
